# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [21]:
print(X)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


AttributeError: 'numpy.ndarray' object has no attribute 'head'

### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [107]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [108]:
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

### Adding the second hidden layer

In [109]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the output layer

In [110]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [111]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [112]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 110)

Epoch 1/110
250/250 [==============================] - 1s 923us/step - loss: 0.5332 - accuracy: 0.7779
Epoch 2/110
250/250 [==============================] - 0s 896us/step - loss: 0.4364 - accuracy: 0.8169
Epoch 3/110
250/250 [==============================] - 0s 857us/step - loss: 0.4028 - accuracy: 0.8292
Epoch 4/110
250/250 [==============================] - 0s 931us/step - loss: 0.3844 - accuracy: 0.8380
Epoch 5/110
250/250 [==============================] - 0s 837us/step - loss: 0.3744 - accuracy: 0.8422
Epoch 6/110
250/250 [==============================] - 0s 930us/step - loss: 0.3673 - accuracy: 0.8453
Epoch 7/110
250/250 [==============================] - 0s 1ms/step - loss: 0.3640 - accuracy: 0.8494
Epoch 8/110
250/250 [==============================] - 0s 872us/step - loss: 0.3603 - accuracy: 0.8486
Epoch 9/110
250/250 [==============================] - 0s 842us/step - loss: 0.3578 - accuracy: 0.8509
Epoch 10/110
250/250 [==============================] - 0s 845us/step - los

250/250 [==============================] - 0s 927us/step - loss: 0.3309 - accuracy: 0.8634
Epoch 81/110
250/250 [==============================] - 0s 841us/step - loss: 0.3302 - accuracy: 0.8639
Epoch 82/110
250/250 [==============================] - 0s 844us/step - loss: 0.3300 - accuracy: 0.8650
Epoch 83/110
250/250 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8630
Epoch 84/110
250/250 [==============================] - 0s 980us/step - loss: 0.3297 - accuracy: 0.8639
Epoch 85/110
250/250 [==============================] - 0s 845us/step - loss: 0.3300 - accuracy: 0.8636
Epoch 86/110
250/250 [==============================] - 0s 901us/step - loss: 0.3300 - accuracy: 0.8635
Epoch 87/110
250/250 [==============================] - 0s 842us/step - loss: 0.3304 - accuracy: 0.8637
Epoch 88/110
250/250 [==============================] - 0s 839us/step - loss: 0.3301 - accuracy: 0.8630
Epoch 89/110
250/250 [==============================] - 0s 819us/step - loss: 0

### Predicting the Test set results

In [113]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 816us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [114]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1524   71]
 [ 205  200]]


0.862